/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package moipackage;

import java.awt.Font;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;  
import com.itextpdf.text.FontFactory;  
import com.itextpdf.text.PageSize;  
import com.itextpdf.text.Paragraph;  
import com.itextpdf.text.pdf.CMYKColor;  
import com.itextpdf.text.pdf.PdfWriter;  

/**
 *
 * Veto Bishop
 * CSIS 643-D01
 * 
 **/
public class OMIDashboard extends javax.swing.JFrame {
    int c,cid;
    int d, oid;
    int e, inid;
    String s2=null;
    String costing = null;
    String percentSplit = null;
    String orderN = null;
    String TotalAmtDue;
    String cEmail = null;

    //constructor
    public OMIDashboard() {
        super("OMI Dashboard");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
       
        try {
            Class.forName("com.mysql.jdbc.Driver");       
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/omidb","root","root");
            String query = "select max(clientid) from registernewclient";
            Statement statmnt = con.prepareStatement(query);
            ResultSet result = statmnt.executeQuery(query);               
            if (result.next())
            {   
               String strEid = result.getString(1);                   
               c = Integer.parseInt(strEid);
               c++;
               cid = c;
               cIdTF.setText(Integer.toString(cid));
            }
        } catch (Exception e) {
            System.out.println("Client ID not found");
        }
         
         try {
            Class.forName("com.mysql.jdbc.Driver");       
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/omidb","root","root");
            String query = "select max(orderid) from orderdetails";
            Statement statmnt = con.prepareStatement(query);
            ResultSet result = statmnt.executeQuery(query);               
            if (result.next())
            {   
               String strEid = result.getString(1);                   
               d = Integer.parseInt(strEid);
               d++;
               oid = d;
            oIdTF.setText(Integer.toString(oid));
            }
        } catch (Exception e) {
            System.out.println("Order ID not found");
        }  

          try {
            Class.forName("com.mysql.jdbc.Driver");       
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/omidb","root","root");
            String query = "select max(invid) from invoice";
            Statement statmnt = con.prepareStatement(query);
            ResultSet result = statmnt.executeQuery(query);               
            if (result.next())
            {   
               String strInid = result.getString(1);                   
               e = Integer.parseInt(strInid);
               e++;
               inid = e;
            it1.setText(Integer.toString(inid));
            }
        } catch (Exception e) {
            System.out.println("Invoice ID not found");
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        cIdTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        t10 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        oIdTF = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        t12 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        t13 = new javax.swing.JTextField();
        t5 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel43 = new javax.swing.JLabel();
        sonTF = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        it2 = new javax.swing.JTextField();
        it3 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        it4 = new javax.swing.JTextField();
        emailInvoice = new javax.swing.JButton();
        previewInvoice = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        it1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Register New Client");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Company Name ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Company Tax ID Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Company Address(City, State, Country)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Company Email Address");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Company Phone Number");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Register");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Clear Form");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Unique Client ID");

        cIdTF.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel37))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cIdTF))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Register New Client  ", jPanel2);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Enter Order Details Here");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Client Name");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Tolerance");

        cb1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select Product Name From List-", "1,1,2-Dodecanediamine", "1,2,4-Trimethylbenzene", "1,2-Butadiene", "1,2-Dibromoethane", "1,2-Dichloroethane", "1,2-Dichloroethene", "1,2-Dichloropropane", "1,2-Dimethoxy Ethane", "1,2-Epoxy Butane", "1,2-Propandiol", "1,3 Dicholorpropene", "1,3-Butadiene", "1,3-Butanediol", "1,3-Pentadiene", "1,3-Propanediol", "1,4-Butanediol", "1,6-Hexanediol", "1-Decene Dimer Hydro", "1-Decene Homopolymer Hydrogenated", "1-DECENE TRIMER AND TETRAMER, HYDROGENATED", "1-Eicosene", "1-Hexadecene", "1-Hexene", "1-Methoxy-2-Propanol ", "1-Methylnaphthalene", "1-Octadecene", "1-Octene", "1-pentanol", "1-Tetradecene", "2 – ethylhexanoic acid", "2 EH Nitrate", "2,2,2-Trifluoroethanol", "2,2,3,3-Tetrafluoropropanol-1", "2,4-Dichlorophenol", "2EHA 50", "2EHA 60", "2-Ethyhexyl Chloroformate", "2-Ethyl Hexanol", "2-Ethylhexanoyl Chloride", "2-Ethylhexyl Acrylate", "2-Ethylhexyl Methacrylate", "2-Hydroxy Ethyl Methacrylate", "2-mercaptoethanol", "2-Methyl-2-butene", "2-Methylimidazole", "2-propoxyethanol", "2-Vinyltoluene", "3043 - TDS+CCS", "3080 - TDS+CCS", "4-TBC 85% in Methanol", "5-Ethylidene - 2 - norborene", "5-Methylhexan-2-one", "Acetaldehyde", "Acetic Acid", "Acetic Anhydride", "Acetone", "Acetone for Col Chem Sol", "Acetonitrile", "Acetyl Chloride", "Acetylacetone", "Acrylamide", "Acrylic Acid", "Acrylonitrile", "Acrylonitrile Solutia Monthly", "Acrylonitrile Solutia Quarterly", "Additive", "Adhesive(Unknown Hazard)", "ADO", "Air Conditioning Fluid", "Air Products Toluene", "Alcohol", "Alcohol Monomer", "Alcohols, C12-16, ethoxylated", "Alimet", "Alkene C18 ", "Alkene C30 H62", "Alkenes C13-C14", "Alkenes C16-C18", "Alkenes C20-C24", "Alkenes C24-C28", "Alkosynt IT 90", "Alkylate", "Allyl Alcohol", "Alpha Methylnaphthalene", "ALPHA OLEFIN C10", "ALPHA OLEFIN C12", "ALPHA OLEFIN C14", "ALPHA OLEFIN C6", "ALPHA OLEFIN C8", "Alpha Olefins", "AlphaPlus C26-28", "American Styrenics", "Amine", "Amino trimethylene Phosphonic Acid", "Ammonia", "Ammonia Solution", "Ammonium", "Ammonium Acetate", "Ammonium Acetate Solution", "Ammonium Bisulfite", "Ammonium Chloride", "Ammonium Dihydrogen Phosphate", "Ammonium Hydrogen Fluoride", "AMODRILL 1000", "Andercol SA", "Anhydrous Ethanol", "Aniline", "ANO Diesel", "Anti-Freeze", "Arab Extra Light ", "Arab Heavy ", "Arab Light ", "Arab Medium", "Ardema Dimethyl Disulfide", "Arkema Butyl Acrylate", "Arkema Ethyl Acrylate", "Aromatic Concentrate", "Aromatic Solvent", "Arsine", "Asphalt", "ASTM D0841 Toluene Specifications", "ASTM D2359 Benzene", "ASTM D396 Fuel Oil No. 1 S500", "ASTM D396 Fuel Oil No. 1 S5000", "ASTM D396 Fuel Oil No. 2 S500", "ASTM D396 Fuel Oil No. 2 S5000", "ASTM D396 Fuel Oil No. 4", "ASTM D396 Fuel Oil No. 4 Light", "ASTM D396 Fuel Oil No. 5 Heavy", "ASTM D396 Fuel Oil No. 5 Light", "ASTM D396 Fuel Oil No. 6", "ASTM D6751 S15 Biodiesel", "ASTM D975 Diesel No. 1-D S15", "ASTM D975 Diesel No. 1-D S500", "ASTM D975 Diesel No. 1-D S5000", "ASTM D975 Diesel No. 2-D S15", "ASTM D975 Diesel No. 2-D S15 if CP<-12C", "ASTM D975 Diesel No. 2-D S500", "ASTM D975 Diesel No. 2-D S500 ifCP<-12C", "ASTM D975 Diesel No. 2-D S5000", "ASTM D975 Diesel No. 2-D S5000ifCP<-12C", "ASTM D975 Diesel No. 4-D", "ASTRA Ethanol", "Astra Industrial Ethanol", "Astra/Cargill Ethanol", "Atmospheric Gas Oil ", "Atmospheric Tower Bottoms", "Avgas", "Aviation Fuel D1655 - Jet A", "Aviation Fuel D1655 - Jet A1", "Aviation Gasoline D910 100LL", "B3043 - TDS+CCS", "B3060 - TDS+CCS", "B3180 - TDS+CCS", "Bakken Crude Oil", "Banole - biodegradable spray oil  from Total", "Barrierpro-17", "Base Oil", "Base Oil aramcoULTRA 2 (60 Neutral)", "Base Oil aramcoULTRA 3 (70 Neutral)", "Base Oil aramcoULTRA 4 (100 Neutral)", "Base Oil aramcoULTRA 6 (150 Neutral)", "Base Oil aramcoULTRA 8 (250 Neutral)", "BASF Brazil", "BASF Chile", "BASF Toluene", "Bayer Toluene", "Bayhibit AM", "Benzaldehyde", "Benzene", "Benzene Chloride", "Benzene D2359", "Benzene for INEOS NOVA LLC - Deer Park", "Benzyl Alcohol", "Benzyl Butyl Phthalate", "Benzyl Toluene", "Biodiesel", "Biodiesel blend with diesel fuel - B5", "Biodiesel D6751 S15 ", "Biodiesel EN ISO", "Biphenyl", "Bitumen", "BOP Cyclics", "Borol Solution", "BP ECO Prior Car", "BP ECO Shore Tank", "BP Ethyl Alcohol for TC", "BP Ethyl Alcohol Gasoline Blend for TC", "BP Light Cycle Oil", "BP Shell Methyl Proxitol - Dockline", "BP Shell Methyl Proxitol - Heel", "BP Shell Methyl Proxitol - Shore Tank", "BP Shell MP - Dock Line", "BP Shell MP - Final", "BP Shell MP - Shore Tank", "BP Shell MP- Heel", "BP_TC_SHIP_MUREX_FINAL", "BP_TC_SHORE_MUREX", "BP_TC_SHORE_TK", "BP_TC_ST_BUNGE", "BP_Vessel_BUNGE", "Brake Fluid", "Brake Fluid 1B71", "Brazilian Diesel 1600 ppm S", "Brazilian Diesel 500 ppm S", "Brine", "BS150 Renkert Base OIl", "BTX - Benzene, Toluene, Xylene Blend", "But-1-ene", "Butadiene", "Butane", "Butanol", "Butanone", "Butanone Oxime", "Butene-1", "Butoxpolyglycol Basic", "Butoxypolyglycol", "Butoxypropylamine", "Butoxytriglycol", "Butyl Acetate", "Butyl Acrylate", "Butyl Carbitol Solvent", "Butyl Cellosolve Solvent", "Butyl Diglycol", "Butyl Iodide", "Butyl Methacrylate", "butyraldehyde", "C1618 ISOMERIZED OLEFIN", "C20 Cataylist Diluent", "C21 - Cis-9-heneicosene", "C30+ Alpha Olefins Fraction  ", "C30+ HA ", "C667", "C670", "C8", "C9-Resinfeed", "CA PMI Fuel Oil A", "CA PMI Fuel Oil B", "CA RMG 380 Specs", "CA RMG 500 Specs", "CA RMK 500 Specs", "Calcium Bromide", "Calcium Carbonate", "Calcium Chloride", "Calcium Hydroxide", "Calcium Hypochlorite", "Calcium Phosphate", "Calcium Stearate", "Canola Oil", "Carbon Black Feedstock", "Carbon Black Oil", "Carbon Dioxide", "Carbon Disulfide", "Carbon Tetrachloride", "Carbowax Glycol 750", "Cargill Reflux Ethanol", "Cascade Chinook Crude Oil", "Catalytic Crack-Distillation Slurry", "Caustic", "Caustic Soda", "CERIFLOW™ 5200", "Chevron Jet Fuel (Pascagoula)", "Chevron MOGAS 88 (RUG)", "Chevron MOGAS 91", "Chevron MOGAS 95 (PUG)", "Chilean COPEC Diesel A-1 (F5)", "Chilean Diesel", "Chiliean ULSD", "Chloroethylene", "Chloroform", "CHO / Gas Oil", "Choline Chloride", "CITGO - Light Cycle Oil", "CITGO Ext - Light Cycle Oil", "Coconut Oil", "Colonial ,  Neat  CBOB, RBOB,PBOB", "Colonial 51 (aviation) Delivery", "Colonial 51 (aviation) Origin", "Colonial 54 Aviation Kerosene, Delivery", "Colonial 54 Aviation Kerosene, Origin", "Colonial 55 Aviation Kerosene, Delivery", "Colonial 55 Aviation Kerosene, Origin", "Colonial 61 3/15-7/31 Summer", "Colonial 61 8/1-3/14 Winter", "Colonial 67 Heating Oil Summer Delivery", "Colonial 67 Heating Oil Summer, Origin", "Colonial 67 Heating Oil Winter Delivery", "Colonial 67 Heating Oil Winter, Origin", "Colonial 77 Heating Oil Summer", "Colonial 77 Heating Oil Winter", "Colonial 88 Heating Oil Summer", "Colonial 88 Heating Oil Winter", "Colonial A CBOB ", "Colonial A1 CBOB blended with Ethanol", "Colonial A1 CBOB with Ethanol", "Colonial A2 CBOB ", "Colonial A3 CBOB ", "Colonial A4 CBOB ", "Colonial A5 CBOB ", "Colonial D1 CBOB with Ethanol", "Colonial D2 CBOB with Ethanol", "Colonial D3 CBOB with Ethanol", "Colonial D4 CBOB with Ethanol", "Colonial D5 CBOB with Ethanol", "Colonial F1 RBOB with Ethanol", "Colonial F2 RBOB with Ethanol", "Colonial F3 RBOB with Ethanol", "Colonial F4 RBOB with Ethanol", "Colonial F5 RBOB with Ethanol", "Colonial H1 PBOB with Ethanol", "Colonial H1 PBOB with Ethanol-Spec VOC", "Colonial H2 PBOB with Ethanol", "Colonial H3 PBOB with Ethanol", "Colonial H4 PBOB with Ethanol", "Colonial H5 PBOB with Ethanol", "Colonial M1 Conventional Gasoline", "Colonial M1 Gasoline Neat", "Colonial M2 Conventional Gasoline", "Colonial M3 Conventional Gasoline", "Colonial M4 Conventional Gasoline", "Colonial M5 Conventional Gasoline", "Colonial S0 CBOB with Ethanol", "Colonial S1 CBOB with Ethanol", "Colonial S2 CBOB with Ethanol", "Colonial S3 CBOB with Ethanol", "Colonial S4 CBOB with Ethanol", "Colonial T1 PBOB with Ethanol", "Colonial T1 POBO with Ethanol", "Colonial T2 CBOB with Ethanol", "Colonial T2 PBOB with Ethanol", "Colonial T3 CBOB with Ethanol", "Colonial T3 PBOB with Ethanol", "Colonial T4 PBOB with Ethanol", "Colonial V1 Conventional Gasoline", "Colonial V1 Conventional Gasoline etho", "Colonial V2 Conventional Gasoline", "Colonial V3 Conventional Gasoline", "Colonial V4 Conventional Gasoline", "Colonial V5 Conventional Gasoline", "Columbian ULSD 30 ppm s", "Compressor Lubricant", "Concentrate", "Condensate", "Condensate Oil", "Condensate Water", "Conoco Philips Hexane Final", "ConocoPhillips Kerosine", "Coolant", "COP - Jet A-1", "COPEC Chile Spec", "COPEC SA Petroleo Diesel A1", "CPChem Methanol Wall Wash Test Spec.", "CPChemMEOH WallWash Benzene prior cargo", "Crank Case Engine Oil", "Creosote", "Crude Benzene", "Crude Butadiene", "Crude Oil", "Crude Tall Oil", "Crude Xylene", "Crylic Acid", "CT Exxon Mobil 1159&1709 IMTT 2Oil Tank", "CT Lyondell Undenatured Ethanol 99.3", "CT Morgan Stanley IMTT Tank Short Slate", "CT New York State Gasoline", "CT Shell Trading Canada Ethanol", "CT Sprague ULSD NYCTA December", "CT Sprague ULSD NYCTA February", "CT Sprague ULSD NYCTA January", "CT Sprague ULSD NYCTA March", "CT Sprague ULSD NYCTA November", "CT Sprague ULSD NYCTA summer 4/1-10/31", "Cumene", "Cutterstock", "Cyclohexane", "Cyclohexanone", "Cyclopentane", "D.E.R. 331 EPOXY RESIN", "D910 Aviation Gasoline grade 100", "D910 Aviation Gasoline grade 100LL", "D910 Aviation Gasoline grade 100VLL", "Decalin", "Decane", "Decanted Oil", "Decene", "DEF STAN 91-90 Issue 3 Av Gas", "DEF STAN 91-91 JET Issue 7", "Deionized Water", "Delayed Coker Oil", "Denatonium Benzoate", "Denatured Methanol", "Dephenolized Cresylic Acid", "DESC F76", "DESC JP-4 Full Test", "DESC JP5", "DESC JP8 B2", "Dexco Polymers LP - Isoprene", "DFSC JP-5 Full Test", "DFSC JP8 Air Force 1", "DHP", "Diacetone Alcohol", "Dialkyl Carbonate", "Dibenzothiophene", "Dicalcium Phosphate", "Dichloromethane", "Dicyclohexylamine", "Dicyclopentadiene (DCPD)", "Diesel", "Diesel Blendstock", "Diesel Oil", "Diesel Winter Specs for LoneStar ", "Diethanolamine", "Diethylamine", "Diethylene Glycol", "Diethylene Glycol Diethyl Ether", "Diethylene Glycol Dimethyl Ether", "Diethylene Glycol Methyl Ether Acetate", "Diethylene Glycol Methyl Ethyl Ether", "Diethylene Glycol Monobutyl Ether", "Diethylene Glycol Monoethyl Ether", "Diethylene Glycol Monoethyl Ether Acetat", "Diethylenetriamine", "Difluoroethane", "Dihexylamine", "Diisobutyl Ketone", "Diisobutylene", "Diisononyl Phthalate", "Diisopropyl Ether", "Dimer Solution", "Dimethyl Disulfide", "Dimethyl Ether", "Dimethyl Ketone", "Dimethyl Phthalate", "Dimethyl Silicone", "Dimethyl Silicone Oil", "Dimethyl Sulfoxide", "DIPA", "Diphenyl Ketone", "Diphenyl Oxide", "Dipropylene Glycol", "Dipropylene Glycol Monomethyl Ether", "Distillate", "DMAC", "DO Petrobras Hexane Dockline", "Docosene (C20-C24)", "Dodecene", "Dodecyl Benzene", "Dow 1-Octene", "Dow Aniline Tars", "Dow Butoxytrigl", "Dow Chemical Tergitol 15-S-5 Surfactant", "dow EEP Solvent", "Dow Ethanol 190 Proof", "Dow Ethanol 192 Proof", "Dow Ethyl Acrylate", "Dow Methyl Carbitol 2011 00127381specs", "Dow Methyl Carbitol-Dow Methods", "Dow MIPA", "Dow Naphtha Composite (Barge Composite)", "Dow Naptha Barge Compartment", "Dow Naptha Barge Composite", "Dow PRIMENE MD Amine", "Dow TEA", "DOW TIPA", "DOW Triisopropanolamine 101", "Dow Vinyl Acetate", "Dow/Shell Naphtha", "DOW/VALERO Naphtha", "Dowanol", "Dowtherm", "Dowtherm A", "DP 1st Ft Vinyl Acetate Monomer Vopak", "DP 2-Ethylhexyl Acrylate", "DP ConocoPhillips Methanol Wall Wash", "DP Dow Methyl Acrylate ", "DP Methanol Wall Wash Test Spec.", "DP Motiva Star 12 for Deer Park", "DP Motiva Star 3 for Deer Park", "DP Motiva Star 5+ for Deer Park", "DP Motiva Star 6 for Deer Park", "DP Neste Oil Nexbase3030", "DP Nonene ST", "DP P&G CE-1095 (10226245) Methyl Esters", "DP P&G CE1095Koshe(10275351)MethylEster", "DP P&G CE-1618 Methyl Esters", "DP P&G CO1055HR(10270429)Fatty Alcohols", "DP P&G CO-1098(10270059) Fatty Alcohols", "DP P&G CO1098Kosher(10270177) Fatty Alc", "DP P&G CO-1214(10220263) Fatty Alcohols", "DP Pearl GTL Base Oil 4 cSt (BO-4)", "DP Pearl GTL Base Oil 4 cSt (BO-4) QHVI", "DP Pearl GTL Base Oil 8 cSt (BO-8)", "DP Pearl GTL QHVI3 3 cSt (BO-3)", "DP Pearl GTL XHVI3 3 cSt (BO-3)", "DP PMI Alkylate 92", "DP Spectrasyn 10", "DP Spectrasyn 100 STK", "DP Spectrasyn 100TC/TT Tank cars/trucks", "DP Spectrasyn 12 RC/T", "DP Spectrasyn 150 ST Elite", "DP Spectrasyn 150TC/TT Elite", "DP Spectrasyn 2", "DP Spectrasyn 2 S/T", "DP Spectrasyn 4", "DP Spectrasyn 4 S/T", "DP Spectrasyn 40", "DP Spectrasyn 40 S/T", "DP Spectrasyn 6", "DP Spectrasyn 6 S/T", "DP Spectrasyn 6D", "DP Spectrasyn 6D S/T", "DP Spectrasyn Elite 65", "DP Spectrasyn Plus 4", "DP Spectrasyn Plus 4 S/T", "DP Spectrasyn Plus 6 ", "DP Spectrasyn Plus 6 M/O", "DP Spectrasyn Plus 6 S/T", "DP Spectrasyn Ultra 150 ", "DP Synesstic 12", "DP Synesstic 12 S/T", "DP Toluene TDI ASTM D5606", "DP Valero VGO", "DPG-Industrial Grade LYB", "DPO-BSA with Stabilizer", "Dripolene", "DuraClear Crystal 7 RSD", "DURASYN 128", "DURASYN 145", "DURASYN 164", "DURASYN 166", "Eagle Ford Crude Oil", "East Texas Sour Crude Oil", "East Texas Sweet Crude Oil", "Eastman Butanol", "Effluent", "EHC 45  TRUCKS for EXXON", "EHC 45 for DP", "EHC 60 Lube Oil for Exxon", "EHC60 TRUCKS for EXXON", "Electrical Insulating Oil", "EN 15376 : 2007 / FprA1:2009", "EN 15376 Ethanol Slate", "EN 590 BK SUMMER", "EN 590 Diesel 2 Class", "EN590 France ULSD Winter", "EN590 IDF Diesel", "Eocene ", "Epichlorohydrin", "Epoxy Resin", "Ester", "Ethane", "Ethanol", "Ethanol Anhydrous", "Ethanol ASTM D4806", "Ethanol for BP Murex/Vitol", "Ethanol for BP Murex/Vitol 10ppm S", "ethanol methanol - Lyondell", "Ethanolamine", "Ethene", "Ethlyene Dichloride (EDC)", "Ethyl Acetate", "Ethyl Acrylate", "Ethyl Alcohol", "Ethyl Alcohol for Texas City - Final", "Ethyl Diglycol", "Ethyl t-Butyl Ether", "Ethyl-3-ethoxypropionate", "Ethylamine", "Ethylbenzene", "Ethylene", "Ethylene Carbonate", "Ethylene Diamine", "Ethylene Dibromide", "Ethylene Dibromide (EDB)", "Ethylene Glycol", "Ethylene Glycol Ethyl Ether", "Ethylene Glycol Monobutyl Ether", "Ethylene Oxide", "Ethyltetrahydrofurfurylether", "Explorer 45 (summer)(10.0)", "Explorer 45(FALL-11.5)", "Explorer 45(Winter-14.5)", "Explorer 4C/4S with Ethanol", "Explorer 4C/4S with Neat", "Explorer 4U with Ethanol", "Explorer Blended 4 Class D - 5", "Explorer Blended 4 Class E-6", "Explorer Blended Class A - 2", "Explorer Blended Class AA-1", "Explorer Blended Class B - 3", "Explorer Blended Class C - 4", "Explorer Neat 4 Class D - 5", "Explorer Neat 4 Class E-6", "Explorer Neat Class A - 2", "Explorer Neat Class AA-1", "Explorer Neat Class B - 3", "Explorer Neat Class C - 4", "Exxon AVGAS arfter Load", "Exxon AvGas Full Slate", "Exxon Diesel Fuel", "Exxon Jet Fuel A1", "Exxon Marine Residual Fuels", "Exxon Premium Mogas", "Exxon Ultra Low Sulfur Diesel", "Exxon/ BP ULSD", "Exxsol D110", "Exxsol D110/D80 Blend", "Exxsol D80", "EXXSOL Heptane ST", "EXXSOL Hexane Fluid", "F-76", "Fatty Acid Distillants", "Fatty Acid Methyl Ester", "FATTY ACIDS, C16-18", "Fatty Alcohol", "Fatty Alcohols", "Feb&Sept-Oct 341 TEPP Enterprise(11.5)", "Fluorobenzene", "Formaldehyde", "Fuel Gas", "Fuel Group-Rio Energy AVGAS D10", "Fuel Oil", "Fumaric Acid", "Furfural", "Future Foam POLYOL Rail Car", "Future Form POLYOL Rail Car", "Gas (>0.1% BENZENE,<1% HEXANE, <1% TOLUENE, <100ppm H2S)", "Gas", "Gas Condensate", "Gasohol", "Gasoil", "Gasoil Blend Component", "Gasoil YPF", "Gasoline", "GASOLINE GRADE TERT BUTYL   ALCOHOL", "Gearbox Lubricant", "Glacial Acetic Acid", "Glycerin", "Glycerol", "Glyceryl Monostearate", "Glycol", "Glycol Ether", "Glycol Ether DPM", "Glycol Ether DPM for Lyondell", "Glycol Ether PM Acetate for Lyondell", "Glycol Ether PM Solvent for Lyondell", "Grease", "Green Earth B100", "Heat Transfer Fluid", "Heat Transfer oil", "Heating Oil", "Heavy Aromatic Fuel Oil", "Heavy Aromatic Oil", "Heavy Cat Cracked Gasoline (HCCG)", "Heavy Cat Cracked Spirit (HCCS)", "Heavy Cycle Oil", "Heavy Fuel Oil", "Heavy Gasoil", "Heavy Naphtha", "Heavy Oil Products", "Heavy Paraffinic", "Heavy Vacuum Gas Oil", "Helium Compressed", "Heptamethyl Nonane", "Heptane", "Hexachlorobenzene", "Hexane", "Hexane 40/45 SHR", "Hexene", "High Sulfur Diesel", "High Sulphur Fuel Oil", "HiTEC® 6590C  Gasoline Fuel Additive", "HRJ-16450", "HRJ-16480", "HRJ-16581", "Hydradd 2703", "Hydraulic Lubricant", "Hydraulic Oil", "HYDRAZINE SOLUTION, 35% ", "HYDRAZINE SOLUTION, 64%", "Hydrocarbon", "Hydrochloric Acid", "Hydrogen Fluoride", "Hydrogen Peroxide", "Hydroquinone", "Hydrotreated Distillate", "Idemitsu Chemicals Decene", "IMPCA Methanol", "Improquim SA", "Indorama Antifreeze for Bayport", "Industrial Ethanol for Seacor/Lansing", "Industrial Oil", "Ineos Amodrill 1000", "Ineos Hexene Wall Wash Specifications", "INEOS NOVA MF305 STYRENE", "Ineos-Nova LLC MF305 Styrene EOM", "Ineos-Nova LLC Styrene EOM", "Ineos-Nova LLC TK202 Styrene EOM", "Ineos-Nova TK202 Strene ", "Iso Propyl Alcohol", "Iso Propyl Benzoate", "isoAmyl Alcohol", "Isobutane", "isoButanol", "isoButene", "isoButyl Acetate", "iso-Butyl Amine", "Isobutylene", "ISOBUTYRIC ACID (IHOBU)", "Isodecanoic Acid", "Isoeicosane", "Isomerate", "Isononanol", "Isooctane", "Isopar", "Isopar C Fluid", "Isopar C Fluid S/T", "Isopar E Fluid ST", "Isopar E Spec ST", "Isopar H Fluid", "isoPentane", "Isoprene", "isopropanol", "isopropanol CBM", "isoPropyl Acetate", "isoPropyl Alcohol", "Isopropyl Ether", "Isopropyl Ether S/T", "isoPropylbenzene", "Isoprpyl_acetate", "Itochu Acrylonitrile Full", "JAYFLEX DIDP", "JAYFLEX DIDP-E", "JAYFLEX DINP", "JEFFADD MW-781", "JEFFCAT DMCHA LO", "Jet  A1", "Jet Fuel", "JX NIPPON AS-110", "Kearl Crude", "Kerosene", "Kerosene / Jet A", "Kuwait", "L7 CBOB Blended with10% ", "L7 CBOB Neat Volatility Specs", "Lanxess Petroflex", "LCO Refinery Import Specs(winter)", "LCO Refinnery Import Specs-Summer", "Lead Replacement Gasoline", "Lean Amine", "Lean MEA", "Light Benzene", "Light Cat Cracked Gasoline (LCCG)", "Light Cat Cracked Naphtha (LCCN)", "Light Cat Cracked Spirit (LCCS)", "Light Cycle Oil", "Light Fuel Oil", "Light Gas Oil", "Light Naphtha", "Light Paraffine", "Light Straight Run Gasoline", "Light Virgin Naphtha", "Linear Alkyl Benzene", "Liquid Petroleum Gas", "Lithium Bromide", "Lithium Chloride", "Lithium Hydroxide", "Lithium Hydroxide Monohydrate", "Lone Star Gasoline Summer", "Lone Star Gasoline Winter", "Lone Star Natural Gasoline Routine 6 ", "Low Sulfur Diesel", "Low Sulphur Fuel Oil (LSFO)", "Low Sulphur Gasoil", "Lubrication Oil", "Lubrizol Product 121.89", "Lubrizol® 9684", "Lubrizol® CV6506", "LYONDELL BDO", "Lyondell Benzene", "Lyondell Bio-ETBE", "Lyondell Brazil", "LYONDELL Common Wall Wash", "Lyondell Diethylene Glycol - Industrial", "LYONDELL DipropyleneGlycol - Fragrance", "LYONDELL DipropyleneGlycol - Industrial", "LYONDELL DipropyleneGlycol DSG ", "Lyondell Europe Styrene", "LYONDELL Glacial Acetic Acid", "LYONDELL Glycol Ether DB", "LYONDELL Glycol Ether DE", "LYONDELL Glycol Ether DM - Jet Fuel Gd", "LYONDELL Glycol Ether EB", "LYONDELL Glycol Ether EB Acetate", "LYONDELL Glycol Ether HE", "LYONDELL Isopropyl Alcohol", "Lyondell Monoethylene Glycol -Industrial", "LYONDELL MPD", "LYONDELL N-Methyl Pyrrolidone (NMP)", "LYONDELL Propylene Carbonate (PCHP)", "LYONDELL Propylene Glycol Industrial", "LYONDELL Propylene Glycol USP Grade", "Lyondell Propylene Oxide ", "Lyondell Propylene Oxide Line", "lyondell Propylene Oxide ship 1st Ft", "Lyondell Reformate", "Lyondell RFO 639 Vopak DP", "Lyondell Styrene ", "LYONDELL Triethylene Glycol-Industrl", "LYONDELL Tripropylene Glycol Acrylate", "LYONDELL VAM Ship Inhibitor", "Lyondell VAM Wall Wash", "LYONDELL Vinyl Acetate Monomer", "LYONDELL Vinyl Acetate Monomer ", "Machine Oil", "Magellan   Gasoline Neat", "Magellan A (V1) Conv. Gasoline", "Magellan A (V2) Conv. Gasoline", "Magellan A (V3) Conv. Gasoline", "Magellan A (V4) Conv. Gasoline", "Magellan AR (H1) PBOB Gasoline", "Magellan AR (H3) PBOB Gasoline", "Magellan AR (H4) PBOB Gasoline", "Magellan N (M1) Conv. Gasoline", "Magellan N (M2) Conv. Gasoline", "Magellan N (M3) Conv. Gasoline", "Magellan N (M4) Conv. Gasoline", "Magellan Neat B (10.0 DVPE)", "Magellan Neat D (11.5DVPE)", "Magellan Neat D (13.5DVPE)", "Magellan Neat D (9.0 EPA)", "Magellan NR (10.0) RBOB Gasoline", "Magellan NR (11.5) RBOB Gasoline", "Magellan NR (13.5) RBOB Gasoline", "Magellan NR (7.2) RBOB Gasoline", "Magellan NR (F3) RBOB Gasoline", "Magellan V-A4", "Magellan V-B2", "Magellan V-C4", "Magellan V-E5", "Magnesium Chloride", "Magnesium Fluoride", "Magnesium Hydroxide", "Magnesium Oxide", "Maleic Anhydride", "Marine Bunker Fuel Oil", "Marine Diesel Oil", "Mar-sept 341 TEPP for Enterprise (9.0)", "Maya Crude Oil", "M-cresol 70", "MEA", "Melamine", "Mercury", "Mesityl Oxide", "Methacrylic Acid (GMAA)", "Methane", "Methanol", "Methanol ASTM D1152", "Methoxyethanol", "Methyl Acetate", "Methyl Acrylate", "Methyl Cyclohexane", "Methyl Diisocyanate", "Methyl Di-Proxitol (DGME)", "Methyl Ester", "Methyl Ethyl Ketone", "Methyl Hexa Hydrophthalic Anhydride", "Methyl Isoamyl Ketone", "Methyl Isobutyl Ketone", "methyl linoleate", "Methyl Methacrylate", "methyl oleate", "Methyl palmitate", "Methyl Proxitol", "Methyl Proxitol Acetate", "methyl stearate", "Methyl Styrene", "Methyl tert-Butyl Ether", "Methylcyclopentadiene Dimer", "Methylcyclopentane", "methyldiethanolamine", "Methyldiglycol", "Methyl-iso-butyl Carbinol", "Mill Scale", "Mineral Oil", "MIPA", "Mixed Alcohols", "Mixed Aromatic", "Mixed B-B's", "Mixed Xylene", "Molybdenum-EG Catalyst Residue Combustible", "Mono Isopropanolamine", "Monochlorobenzene", "Monoethanolamine", "monoethanolamine", "Monoethylene Glycol", "Monoisopropanolamine", "Monomer Acid", "mono-p-nonylphenyl ether, branched, ethoxylated", "Monopropylene Glycol", "Motiva STAR 4", "MPEG 260", "MTC - Albacora East", "MTC - Albian Residual Blend", "MTC - Altamira", "MTC - Amenam Blend", "MTC - Arab Extra Light", "MTC - Arab Heavy", "MTC - Arab Light", "MTC - Arab Medium", "MTC - Aseng", "MTC - Azeri", "MTC - Basrah Light", "MTC - Bonga for Sutton", "MTC - Bonito Sour", "MTC - Cabinda", "MTC - Cascade Chinook", "MTC - Cold Lake", "MTC - CPC Blend", "MTC - Cusiana", "MTC - Dalia", "MTC - Djeno", "MTC - Doba", "MTC - E4", "MTC - EA", "MTC - Eagle Ford", "MTC - East Texas Sour", "MTC - East Texas Sweet", "MTC - Eocene", "MTC - Erha", "MTC - Escravos", "MTC - Forcados", "MTC - Forties", "MTC - Fosterton", "MTC - Frade", "MTC - Genesis", "MTC - Girassol", "MTC - Gulf Coast B", "MTC - Gulf Coast Light", "MTC - Hamaca Blend", "MTC - Heavy Louisiana Sweet", "MTC - High Island", "MTC - Hoops", "MTC - Hungo", "MTC - Husky Synthetic Blend", "MTC - Illinois Basin", "MTC - Ingleside Sweet", "MTC - Johnson Bayou", "MTC - Jubarte", "MTC - Kearl", "MTC - Kirkuk", "MTC - Kissanje Blend", "MTC - Kuwait", "MTC - Light Louisiana Sweet", "MTC - Louisiana-Mississippi Sweet", "MTC - M-100", "MTC - MacKay River Heavy", "MTC - Mars Blend", "MTC - Maya", "MTC - Midale", "MTC - Mid-Continent Sweet", "MTC - Mixed Blend Sweet", "MTC - New Grade A", "MTC - NKossa", "MTC - North Dakota Light", "MTC - Olende", "MTC - Oriente", "MTC - Oseberg", "MTC - Ostra", "MTC - Palanca", "MTC - Peregrino", "MTC - Plutonio", "MTC - Port Victoria Light", "MTC - Poseidon", "MTC - Premium Albian Synthetic", "MTC - Qua Iboe", "MTC - Ratawi", "MTC - Roncador Heavy", "MTC - Rubiales", "MTC - Saharan Blend", "MTC - South Texas Light", "MTC - Southern Green Canyon", "MTC - Suncor OSA Blend", "MTC - Sunniland", "MTC - Syncrude", "MTC - Urals", "MTC - Vasconia", "MTC - West Hackberry Sweet", "MTC - West Texas Intermediate", "MTC - West Texas Sour", "MTC - Western Canadian Select", "MTC - Wyoming Sweet", "MTC - Xan Coban", "MTC - Yoho", "MTC - Zuata 300", "MTC - Zuata Medium VR20", "MTC - Zuata Medium VR30", "MTC - Zuata Medium VR35", "MTC - Zuata Sweet", "MTC_Domestic Sweet", "N,N-Dimethyl Formamide", "n-amyl propionate", "Naphtha", "Naphtha Reformate", "Naphthalene", "Naphthene K30", "Naphthenic Transformer Oil Base Stock", "Natural Gas", "Natural Gasoline", "n-Butane", "n-Butanol", "n-Butyl Acetate", "n-Butyl Acrylate", "n-Butyl Bromide", "n-Butyl Methyl Acrylate", "n-Decane", "Neo-Decanoic Acid", "Neodecanoic Acid (Exxon)", "Neodene", "Neodol 23-2", "Neodol 23-6.5", "Neodol 25-3 ", "Neodol 25-7", "Neodol 25-7 V2453", "Neodol 25-7 V2634", "Neodol 25-9", "Neodol 25-9 V2454", "Neodol 45-7", "Neopentyl Glycol", "Neopentyl Glycol 90% for OXEA", "n-Heptane", "n-Hexadecane", "n-Hexane", "n-Hexanol", "Nipar", "NIPAR S10", "NIPAR S20", "Nitric Acid", "Nitrobenzene", "Nitroethane", "Nitrogen", "Nitromethane", "n-Methyl Morpholine", "n-Methyl Pyrrolidone(NMP)", "Nonene", "Normal Octyl Mercaptan", "Normal Paraffin C10-C13", "Nov-Feb15-341 TEPP Enterprise(13.5)", "Novidessa", "n-Pentane", "n-Propanol", "n-Propyl Acetate", "n-Propyl Bromide", "NR grade gasoline (RBOB) AA/A Class", "NR grade gasoline (RBOB) B-2", "NR grade gasoline (RBOB) C-3", "NR grade gasoline (RBOB) D-4", "o-Benzoylbenzoic Acid", "Octanol", "Octene", "o-Cyclohexyl-cyclohexanone", "Odorless Mineral Spirits", "Off Gas", "Olefins", "o-Nitrochlorobenzene", "o-Phenylenediamine", "o-Phenylphenol", "Orform SX 80", "o-Toluidine", "o-Xylene", "P&G CO-1214 Fatty Alcohol", "P&G CO-1298(10270041)", "Palm Methyl Ester", "Palm Oil", "Panalane L14E", "PanaX500", "Papi 27 Polymeric MDI", "Paraformaldehyde", "p-Benzoquinone", "p-Chlorotoluene", "Pentadiene", "Pentane", "Pentanol", "Perchloroethylene", "PerkinElmer Nujol-100ml", "Peru-Quimicos", "Peruvian ULSD", "Petrobras Gas Oil 0.18%", "Petrobras Hexane S/Tk vessel", "Petrochem Caromax 28", "Petroleum coke KZA 1st grade GOST 22898", "Petroleum Sour Crude Oil", "Petroleum Distillate", "PFO", "Phenol", "Phenoxycarbonyl (PMAC)", "Phenyl Methanol", "Phillips 66 Gasoline", "Phosphoric Acid", "Phosphorous Acid", "Piperylene", "Plasticizer", "PMI Gasoline", "PMI MTBE", "PNP-TG", "Polioles", "Polybutene", "Polyethylene Glycol", "Polyethylene Glycol Dimethacrylate (Polyurathane Foam)", "Polyethylene Glycol Dimethyl Ether", "Polymeg 2000", "Polymers International", "polymethylene polyphenylisocyanate", "Polyol", "Polystyrene", "Potassium Acetate", "Potassium Bicarbonate", "Potassium Carbonate", "Potassium Hydroxide (Solid)", "Premium Unleaded Gasoline", "Process Oil", "Proctor and Gamble Amines", "Produced Water", "Propane", "Propane/Propylene Mix", "Propionaldehyde", "Propionic Acid", "Propyl Acetate", "Propylene", "Propylene Carbonate", "Propylene Dichloride", "Propylene Glycol", "Propylene Glycol Monoethyl Ether", "Propylene Glycol Monom Ethyl Ether Aceta", "Propylene Glycol Monomethyl Ether", "propylene glycol monomethyl ether acetate, alpha-isomer", "propylene glycol mono-n-propyl ether", "Propylene Oxide", "Propylene Tetramer", "Propylene Trimer", "PX 3872", "PX 4005", "p-Xylene", "Pygas", "Pyridine", "Pyrolysis Gasoline", "Quinica Delta", "Quinoline", "Raff1", "Raffinate", "Raw Py Gas", "RECOPE Diesel 0.0015%S", "RECOPE Diesel 0.05%S", "Reformate", "Refrigerant Oil", "RENKERT STAR 12", "RENKERT STAR 4", "RENKERT STAR 6", "RENKERT STAR SN 500", "Renoil 107 for Renkert", "Renoil 215 for Renkert", "Renoil 625 for Renkert", "Repsol ULSD 15 ppm S", "Residual Fuel Oil", "Resin Oil 80", "Resirene", "REZIFLOW™ 2120", "RFG EPA", "Risella X415 - Shell", "Risella X420 - Shell", "Risella X430 - Shell", "Sabic MEG Fiber Grade for Shell", "sec-Butyl Acetate", "SELEXOL", "SH Dow DIPA", "SH_UCAR_ Filmer_IBT", "Shell - Caradol SC56-16", "Shell Crude Oil, Sour (=>0.5% Sulphur)", "Shell GTL Solvent GS 215", "Shell GTL Solvent GS 270", "Shell GTL Solvent GS 310", "Shell Methanol Wall Wash Caradol Load", "Shell Reformate", "Shell RUL Mexico Gasoline ", "Shell SOL TD-Paraffic Solvent", "Shell untreated naptha full range", "Shore Tank Prior", "Silicon Dioxide", "Silicone Resin", "Siloxane", "Sludge", "SME B99.9", "SN 500 Renkert Base OIl", "Sodium Acetate", "Sodium Benzoate", "Sodium Bicarbonate", "Sodium Bisulfite", "Sodium Borohydride", "Sodium Carbonate", "Sodium chloride", "Sodium Hydrogen Carbonate", "Sodium Hydrosulfide", "Sodium Hydrosulfite", "Sodium Hydroxide (Solid)", "Sodium Hypochlorite", "Sodium Sarcosine", "Sodium Silicofluoride", "Sodium Thiocyanate", "Soil", "Solvent", "Solvent Naphtha", "Soy Methyl Ester", "Specifications for Enterprise RBOB - A", "Specifications for Enterprise RBOB - B", "Specifications for Enterprise RBOB - C", "Specifications for Enterprise RBOB - D", "Spectrasyn  - SPEC ELITE 150 VL", "Spectrasyn 10 S/T", "Spectrasyn 12 S/Tk (XOM synesstic 12st)", "SR 1123", "SR Chevron LCO", "SR Colonial A2 CBOB ", "SR Colonial A2 CBOB - Neat", "SR Colonial F1 RBOB with Ethanol", "SR Neodol Wall Wash Test Spec.", "Styrenated Phenol", "Styrene", "Styrene - Acrylonitrile Copolymer", "Styrene Monomer", "Sulfolane", "Sulfur", "Sulphuric Acid (Sulfuric)", "Sunscreen Spray", "Super Unleaded Gasoline", "Surfactant  ", "Synesstic 5 for Exxon", "Talisman Condensate", "Tallow", "Taminco Methanol", "t-Amyl Alcohol", "Tar", "TBHP-55", "TDI 80", "TDI 80E", "Tergitol", "Tergitol NP9", "Tert-Butyl Acetate", "Tertbutyl Alcohol", "tert-Butylamine", "tert-Dodecyl Mercaptan", "Tetrachloroethylene", "Tetrahydrofuran", "Tetrahydronaphthalene", "Tetramer - Plasticizer", "Texanol Ester Alcohol for Eastman", "Texanol Isobutyrate", "THF@Vopak Deer Park for ISP Chemicals", "Thiophene-2-ethanol", "Titanium Dioxide", "Titanium Tetrachloride", "TME B100", "TME B99.9", "Toluene", "Toluene diisocyanate (TDI)", "Toluene/Xylene Mix", "Toluhydroquinone", "Tower Bottoms", "Trafigura Australia Bio Specs", "Trans-1,2-Dichloroethylene", "Transformer Oil", "Transmission oil", "Transmix", "Transmix- DP-Valero", "Tri-(2-chlorisopropyl) phosphate", "Triacetin", "Trichloroethylene", "Triethanolamine", "Triethylamine", "Triethylene Glycol", "TRIETHYLENE GLYCOL ", "Triethylene Glycol Monoethylether", "Triethylenediamine", "Triethylenetetramine (TETA)", "Trifluoroethanol", "Trimethylpentanediol Disobutrate", "Triphenyl Phosphate", "Tris(hydroxymethyl) nitromethane", "TXIB for Eastman", "UCAR (TM) Ester EEP", "UCAR Filmer IBT", "ULSD EN590 Winter for DP", "Ultra Low Sulphur Diesel", "Ultra Low Sulphur Kerosine", "Ultramar Jet A1", "ULTRAMINA TA 200", "Ultranex NP 90", "Ultrapeg 400", "Undecane", "Undenatured Fuel Grade Ethanol", "Unknown Solid", "Unleaded Gasoline", "Unleaded Motor Spirit", "Used Cooking Oil", "Used Engine Oil", "Vacuum Distillate", "Vacuum Gas Oil", "Vacuum Gas Oil - Cat Feed", "Vacuum Tower Bottoms ", "valeric acid", "Valero Alkylate Full Slate", "Valero Alkylate Limited Testing", "VAM Oxyde Chemical", "Vapor", "Vegetable Oil", "Veova VEM 10 ", "Videolar", "Vinyl Acetate", "Vinyl Acetate Monomer", "Visom 4 for ExxonMobile Lubes ", "Visom 6 for Exxon Mobile Lubes", "Voranol", "wall wash  - Methanol", "Wall Wash Water", "Waste Oil", "Waste Water", "Water", "Water Solution", "Water-Gas Vapor", "White Rose Crude Oil", "XOF 25A", "XTF 959, Crude", "Xylene", "Xylene D843", "Y-Grade Natural Gas Condensate", "YUBASE", "Yubase 3", "Yubase 4", "Yubase 4 Plus", "Yubase 6", "Yubase 6 plus", "Yubase 8", "Zinc Oxide", "Zinc Sulfate", " " }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Client Reference Number");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Equipment Name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Product Grade");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Terminal Name");

        cb2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select Type of Inspection-", "Ship Load", "Ship Discharge", "Lighthering", "Bunker Survey", "Inventory", "Shore tank Sampling", "Railcar Sampling", "Shore Tank Gauging", "Analysis", "Pipeline Transfer", "Wallwash", "Pre-inspection", "Railcar Gauging", "Barge Load", "Barge Discharge", "Shipping", "Witnessing" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Client E-mail");

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Type Of Inspection");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Type of Services");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Name of Trading Partner ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Name of Port");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Estimated startDate/Time");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Percentage Invoice Split");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Generate Order Confirmation");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("Sync to Database");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Unique Order Number ");

        oIdTF.setEditable(false);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Product Name");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Nominated Quantity");

        t5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select Type of Service-", "Quantity Only", "Quality Only", "Q & Q" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(42, 42, 42)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(t1)
                                                .addComponent(t2)
                                                .addComponent(t4)
                                                .addComponent(t6)
                                                .addComponent(t7)
                                                .addComponent(oIdTF)
                                                .addComponent(t5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(58, 58, 58)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel39)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel40))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t10, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cb1, 0, 187, Short.MAX_VALUE)
                                            .addComponent(t8, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(cb2, 0, 1, Short.MAX_VALUE)
                                            .addComponent(t9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(t11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(t12)
                                            .addComponent(t13)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(79, 79, 79))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(t5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Order Entry  ", jPanel4);

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel42.setText("Prepare Invoice");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Unique Invoice Number ");

        sonTF.setBackground(new java.awt.Color(204, 255, 204));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Employee  Number ");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Date/Time");

        it2.setEditable(false);
        it2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                it2ActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Client  Number ");

        it4.setEditable(false);

        emailInvoice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailInvoice.setForeground(new java.awt.Color(0, 102, 102));
        emailInvoice.setText("Email Invoice");
        emailInvoice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        emailInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInvoiceActionPerformed(evt);
            }
        });

        previewInvoice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previewInvoice.setForeground(new java.awt.Color(0, 102, 102));
        previewInvoice.setText("Preview Invoive");
        previewInvoice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        previewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewInvoiceActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 153, 153));
        jLabel47.setText("Search By Order Number");

        it1.setEditable(false);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 102, 102));
        jButton10.setText("search");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(94, 94, 94))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(it2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(it1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(it4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(it3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(sonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(247, 247, 247)))))
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(previewInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(emailInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(315, 315, 315))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(sonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(it3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(it1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(it2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(it4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previewInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Invoice", jPanel6);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/omi-logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(199, 199, 199)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        //search by ID from the data base
        String searchBy;
        searchBy = sonTF.getText();
        try{
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(OMILoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/omidb","root","root");
            Statement st,st2;
            ResultSet rs,rs1 ;
            st = con.createStatement();
            st2 = con.createStatement();
            rs = st.executeQuery("select * from orderdetails");
            rs1 = st2.executeQuery("select * from cost");

            boolean b = false;
            while (rs.next())
            {
                if(rs.getString("orderid").equals(searchBy))
                {
                    b = true;
                    s2 = rs.getString("inspectiontype");
                    percentSplit = rs.getString("perinvoicesplit");
                    cEmail = rs.getString("cemail");
                    it2.setText(rs.getString(8));
                    it4.setText(rs.getString(4));
                }
            }
            while (rs1.next())
            {
                if(rs1.getString("type").equals(s2))
                {
                    costing = rs1.getString("price");
                }
            }

            if(b==false)
            {
                JOptionPane.showMessageDialog(null,"Order ID Not Found\nTry Again");
                s2 = null;
                costing = null;
                sonTF.setText("");
                it2.setText("");
                it3.setText("");
                it4.setText("");
            }

        }catch(SQLException se){}
        catch(NullPointerException ne){}
    }//GEN-LAST:event_jButton10ActionPerformed
    //Invoice total due calculation 
    private void previewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewInvoiceActionPerformed

        String PDFName1=sonTF.getText();
        double TotalDue;
        double costs;
        double per;

        costs = Double.parseDouble(costing);
        per = Double.parseDouble(percentSplit);
        TotalDue = (costs*per)/100.0;
        String tempStr = String.format("%.2f",TotalDue);
        TotalAmtDue = tempStr;

        if(PDFName1.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Can't Create PDF");
        }

        else
        {
            PDFName1 = PDFName1;
            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            try {
                SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy HH-mm-ss");
                Date date = new Date();
                String RName = "D:\\LevelApp Project\\InvoiceOMI\\"+PDFName1+formatter.format(date)+"-INVOICE"+".pdf";

                PdfWriter writer = PdfWriter.getInstance(document, new   FileOutputStream(RName));
                document.open();
                Paragraph paragraph1 = new Paragraph();
                paragraph1.setSpacingBefore(100);
                document.add(paragraph1);
                document.add(new Paragraph("Invoice Details      Date: "+formatter.format(date)+"\n\n",
                    FontFactory.getFont(FontFactory.COURIER, 14, Font.BOLD, new CMYKColor(255, 255, 255, 0))));

            document.add(new Paragraph("Order Number: "+sonTF.getText()+"\n"+"Employee Number: "
                +it3.getText()+"\n"+"Date/Time: "+it2.getText()+"\n"+"Client Number: "
                +it4.getText()+"\n"+"Total Amount Due: "+TotalAmtDue+"\n\n\nThank You",
                FontFactory.getFont(FontFactory.COURIER, 14, Font.PLAIN, new CMYKColor(255, 255, 255, 0))));
        document.close();
        JOptionPane.showMessageDialog(null,"Invoice  Created Successfully as\n"+PDFName1+formatter.format(date)+"-INVOICE"+".pdf");
        }catch(Exception e){}
        }

    }//GEN-LAST:event_previewInvoiceActionPerformed
   
    //send e-mail invoice
    private void emailInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInvoiceActionPerformed

        try{
          
            String from = "rkgaursender@hotmail.com";
            Properties properties = System.getProperties();
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.port", "587");
            properties.put("mail.smtp.host", "m.outlook.com");
            properties.put("mail.smtp.auth", "true");  
            
            Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {

                return new PasswordAuthentication("rkgaursender@hotmail.com", "@786omsairam");

            }

        });
            
            session.setDebug(true);
            MimeMessage message = new MimeMessage(session);
            message.setText("\nHello Customer, Thank you very much for your business! Below is your invoice for this job. If you have any questions, feel free to contact our team.\n\nUnique Invoice  Number:" + it1.getText()+"\n"+"Employee Number: "+it3.getText()+"\n"+"Date/Time: "+it2.getText()+"\n"+"Client Number: "+it4.getText()+"\n"+"Total Amount Due: $"+TotalAmtDue);
            message.setSubject("Invoice Details from Petrospec :");
            message.setFrom(new InternetAddress(from));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(cEmail.trim()));
            message.saveChanges();
           
             Transport transport = session.getTransport("smtp");
             transport.send(message);
             transport.close();

             JOptionPane.showMessageDialog(null,"Invoice Confirmation sent to "+cEmail);
            sonTF.setText("");
            it2.setText("");
            it3.setText("");
            it4.setText("");
        }catch(Exception e){}
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/omidb","root","root");
            Statement st=con.createStatement();
            int i = st.executeUpdate("insert into invoice values('"+it1.getText()+"')");
            inid++;
            it1.setText(Integer.toString(inid));
        }catch(Exception e){}
    }//GEN-LAST:event_emailInvoiceActionPerformed

    private void it2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_it2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_it2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/omidb","root","root");
            Statement st=con.createStatement();
            int i = st.executeUpdate("insert into orderdetails values('"+oIdTF.getText()+"','"+t1.getText()+"','"+t2.getText()+"','"+t3.getText()+"','"+t4.getText()+"','"+t5.getSelectedItem()+"','"+t6.getText()+"','"+t7.getText()+"','"+cb1.getSelectedItem()+"','"+t8.getText()+"','"+cb2.getSelectedItem()+"','"+t9.getText()+"','"+t10.getText()+"','"+t11.getText()+"','"+t12.getText()+"','"+t13.getText()+"')");
            oid++;
            oIdTF.setText(Integer.toString(oid));

            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setSelectedItem("-Select Type of Service-");
            t6.setText("");
            t7.setText("");
            cb1.setSelectedItem("-Select Product Name From List-");
            t8.setText("");
            cb2.setSelectedItem("-Select Type of Inspection-");
            t9.setText("");
            t10.setText("");
            t11.setText("");
            t12.setText("");
            t13.setText("");
            JOptionPane.showMessageDialog(null,"Data Synchronized into Database Successfully");
        } catch (Exception e) {
            System.out.println("Client ID not found");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    //Order confirmation
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            String usemailID = t2.getText();
            String from = "rkgaursender@hotmail.com";
            Properties properties = System.getProperties();
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.port", "587");
            properties.put("mail.smtp.host", "m.outlook.com");
            properties.put("mail.smtp.auth", "true");  
            
            Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {

                return new PasswordAuthentication("rkgaursender@hotmail.com", "@786omsairam");

            }

        });
            
            session.setDebug(true);
            MimeMessage message = new MimeMessage(session);

            message.setText("\nThank you for your nominated! We confirm receipt of your orders and confirm instructions as per below.\n\nUnique Order  Number:" + oIdTF.getText()+"\n"+"Client Name: "+t1.getText()+"\n"+"Client Mail: "+t2.getText()+"\n"+"Reference Number: "+t3.getText()+"\n"+"Equipment Name: "+t4.getText()+"\n"+"Type of Services: "+t5.getSelectedItem()+"\n"+"Trading Partner Name: "+t6.getText()+"\n"+"Estimated Start Date/time: "+t7.getText()+"\n"+"Product Name: "+cb1.getSelectedItem()+"\n"+"Product Grade: "+t8.getText()+"\n"+"Type of Inspection: "+cb2.getSelectedItem()+"\n"+"Terminal Name: "+t9.getText()+"\n"+"Name of Port: "+t10.getText()+"\n"+"Percentage Invoice Split: "+t11.getText()+"\n"+"Tolerance: "+t12.getText()+"\n"+"Nominal Quantity: "+t13.getText());
            message.setSubject("Order Confirmation from Petrospec :");
            message.setFrom(new InternetAddress(from));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(t2.getText().trim()));
            message.saveChanges();
           
             Transport transport = session.getTransport("smtp");
             transport.send(message);
             transport.close();
             transport.close();
             JOptionPane.showMessageDialog(null,"Order Confirmation sent to "+usemailID);
        }catch(Exception e){}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    //insert into data base for order details
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/omidb","root","root");
            Statement st=con.createStatement();
            int i = st.executeUpdate("insert into registernewclient values('"+cIdTF.getText()+"','"+jTextField1.getText()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jTextField5.getText()+"')");
            cid++;
            cIdTF.setText(Integer.toString(cid));

            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            JOptionPane.showMessageDialog(null,"Data Stored Successfully");
        } catch (Exception e) {
            System.out.println("Client ID not found");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OMIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OMIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OMIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OMIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OMIDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cIdTF;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JButton emailInvoice;
    private javax.swing.JTextField it1;
    private javax.swing.JTextField it2;
    private javax.swing.JTextField it3;
    private javax.swing.JTextField it4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField oIdTF;
    private javax.swing.JButton previewInvoice;
    private javax.swing.JTextField sonTF;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JComboBox t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
